### ISSUE TITLE
could you be more specific on how to use your mod

### ISSUE THREAD

**Issue by asomedude9897** [bartimaeusnek/BetterVoidWorlds#2]
i only got in to one dimention and that was the winter dimention.  i didnt know how i did it and when i try to reproduce it gives me errors

**Comment by asomedude9897** [comment]
the only way i was finally able to get to your dimentions was by using comands

**Comment by bartimaeusnek** [comment]
how did you tried to get into the dimensions? if you craft the portals or give them yourself with creative it should not error out. if you try to give them via commands it will error out since the portals are NBT dependant.

**Comment by bartimaeusnek** [comment]
well since i got not answer for 8days, ill close this.

**Comment by Kimapr** [comment]
8 days? really?
