### ISSUE TITLE
private dimensional plate doesnt work

### ISSUE THREAD

**Issue by tomtenberge** [bartimaeusnek/BetterVoidWorlds#4]
private dimensional plate doesnt work when player starts with it in their inventory, and when not given by custom starter gear.  it still randomly fails to initiate teleport

Version: 0.1.0-0.1.0

**Comment by bartimaeusnek** [comment]
you must corretly apply the NBT data for each block. you can not simply give it via console/JEI. Either use Gamemode1 or apply the propper NBT data by hand.

**Comment by tomtenberge** [comment]
can you tell me how to format the correct nbt data?
